apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contact-ingress
spec:
  rules:
    - host: contact.romanolucchesi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contact-api-service
                port:
                  number: 80
